[versions]
agp = "8.5.0"
kotlin = "2.0.21"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
arCore = "1.47.0"
tensorflow = "0.4.0"
mlKitObjectObjectDetection = "17.0.2"
googleLibrariesBom = "19.2.1"
cloudVision = "1.102.0"
coroutines = "1.7.1"
objLoader = "0.2.1"
navigation =  "2.7.6"
roomVersion = "2.6.1"
koinVersion = "4.0.0"
timberVersion = "5.0.1"
retrofitVersion = "2.9.0"
okkHttp = "4.12.0"
chucker = "3.5.2"
firebaseBom = "33.9.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
objectDetection = { module = "com.google.mlkit:object-detection", version.ref = "mlKitObjectObjectDetection" }
customObjectDetection = { module = "com.google.mlkit:object-detection-custom", version.ref = "mlKitObjectObjectDetection" }
arcore = { module = "com.google.ar:core", version.ref = "arCore" }
tensorflow = { module = "org.tensorflow:tensorflow-lite-task-vision", version.ref = "tensorflow" }
googleLibrariesBom = { module = "com.google.cloud:libraries-bom", version.ref = "googleLibrariesBom" }
googleCloudVision = { module = "com.google.cloud:google-cloud-vision", version.ref = "cloudVision" }
kotlinStdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinStdLibJdk = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesPlayServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
objLoader = { module = "de.javagl:obj", version.ref = "objLoader" }
navFragment = {module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation"}
navUi = {module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation"}
navCommon = {module = "androidx.navigation:navigation-common-ktx", version.ref = "navigation"}
safeArgs = {module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation"}
roomRuntime = {module = "androidx.room:room-runtime", version.ref = "roomVersion"}
roomCompiler = {module = "androidx.room:room-compiler", version.ref = "roomVersion"}
roomKtx = {module = "androidx.room:room-ktx", version.ref = "roomVersion"}
koinAndroid = {module = "io.insert-koin:koin-android", version.ref = "koinVersion"}
koinNavigation = {module = "io.insert-koin:koin-androidx-navigation", version.ref = "koinVersion"}
koinCore = {module = "io.insert-koin:koin-core", version.ref = "koinVersion"}
timber = {module = "com.jakewharton.timber:timber", version.ref = "timberVersion"}
retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion"}
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker"}
logginInterceptor =  { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okkHttp"}
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okkHttp"}
firebaseBom = {module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom"}
vertexAi = {module = "com.google.firebase:firebase-vertexai"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
